site_name: GolangDocs
site_url: https://kutt27.github.io/golangdocs/

theme:
  features:
    - navigation.footer
    - content.code.copy
  logo: assets/layers.png
  favicon: assets/favicon.ico
  name: material
  font:
    text: PT Serif
    code: Source Code Pro
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple

nav:
  - Home: index.md
  - Basics:
      - Introduction: "1. Basics/1. Hello-World.md"
      - Go Compiler: "1. Basics/2. Go-Compiler.md"
      - Data Types: "1. Basics/3. Data-Types.md"
      - Standard Library: "1. Basics/4. Standard Library.md"
      - Control Structures: "1. Basics/5. If-and While.md"
      - Conditionals: "1. Basics/6. Conditionals.md"
      - Arrays: "1. Basics/7. Arrays.md"
      - Slices: "1. Basics/8. Slices.md"
      - Maps: "1. Basics/9. Maps.md"
      - Range: "1. Basics/10. Range.md"
      - Functions: "1. Basics/11. Functions.md"
      - Control Flow: "1. Basics/12. Control-Flow-Mechanism.md"
      - Init: "1. Basics/13. Init.md"
  - Intermediate:
      - Closures: "2. Intermediate/1. Closures.md"
      - Recursion: "2. Intermediate/2. Recursion.md"
      - Pointers: "2. Intermediate/3. Pointers.md"
      - Strings and Runes: "2. Intermediate/4. String-and-Runes.md"
      - Formatting-verbs: "2. Intermediate/5. Formatting-Verbs.md"
      - FMT Package: "2. Intermediate/6. FMT-Package.md"
      - Structs: "2. Intermediate/7. Structs.md"
      - Methods: "2. Intermediate/8. Methods.md"
      - Interfaces: "2. Intermediate/9. Interfaces.md"
      - Struct Embedding: "2. Intermediate/10. Struct-Embedding.md"
      - Generics: "2. Intermediate/11. Generics.md"
      - Errors and Custom Error: "2. Intermediate/12. Errors-and-Custom-Error.md"
      - String Functions: "2. Intermediate/13. String-Functions.md"
      - String Formatting: "2. Intermediate/14. String-Formatting.md"
      - Text Templates: "2. Intermediate/15. Text-Templates.md"
      - Regular Expression: "2. Intermediate/16. Regular-Expression.md"
      - Time and Epoch: "2. Intermediate/17. Time-and-Epoch.md"
      - Random Number: "2. Intermediate/18. Random-Number.md"
      - Number Parsing: "2. Intermediate/19. Number-Parsing.md"
      - URL Parsing: "2. Intermediate/20. URL-Parsing.md"
      - Bufio Package: "2. Intermediate/21. Bufio-Package.md"
      - Base64 Coding: "2. Intermediate/22. Base64-Coding.md"
      - Cryptographic Hashing: "2. Intermediate/23. Cryptographic-Hashing.md"
      - Read Write Files: "2. Intermediate/24. Read-Write-Files.md"
      - Line Filters: "2. Intermediate/25. Line-Filters.md"
      - File Paths: "2. Intermediate/26. File-Paths.md"
      - Directories: "2. Intermediate/27. Directories.md"
      - Directories Addon: "2. Intermediate/28. Directories-Addon.md"
      - Command Line: "2. Intermediate/29. Command-Line.md"
      - Environment Variables: "2. Intermediate/30. Environment-Variables.md"
      - Logging: "2. Intermediate/31. Logging.md"
      - JSON: "2. Intermediate/32. JSON.md"
      - Struct Tags: "2. Intermediate/33. Struct-Tags.md"
      - XML: "2. Intermediate/34. XML.md"
      - Go Extensions: "2. Intermediate/35. Go-Extensions.md"
      - Type Conversions: "2. Intermediate/36. Type-Conversions.md"
      - IO Package: "2. Intermediate/37. IO-Package.md"
      - Math Package: "2. Intermediate/38. Math-Package.md"
  - Advanced:
      - Goroutines: "3. Advanced/1. Goroutines.md"
      - Channels: "3. Advanced/2. Channels-and-Unbuffered-Channels.md"
      - Buffered Channels: "3. Advanced/3. Buffered-Channels.md"
      - Select: "3. Advanced/4. Select.md"
      - Concurrency: "3. Advanced/5. Concurrency.md"
      - Rate Limiting: "3. Advanced/6. Rate-Limiting-and-Algorithms.md"
      - Utilities and Sys Ops: "3. Advanced/7. Utilities-and-System-Operations.md"
      - Reflection: "3. Advanced/8. Reflection.md"
      - Stateful Goroutines: "3. Advanced/9. Stateful-Goroutines.md"
  # - Backend:
  #     - Go Backend: "Backend/go-backend.md"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
    - icon: fontawesome/brands/github
      link: https://github.com

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      language_prefix: 'language-'
      linenums: true
      guess_lang: false
      use_pygments: true
      extend_pygments_lang:
        - name: go
          lang: go
        - name: javascript
          lang: javascript
        - name: typescript
          lang: typescript
        - name: c
          lang: c
        - name: cpp
          lang: cpp
        - name: java
          lang: java
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format